### ISSUE TITLE
[Feature] Demo .w3x map with Blizzcon UI

### ISSUE THREAD

**Issue by rufreakde** [UIZorrot/War3re-inmap-graphic-enhance#1]
Hey,
would be nice if there was a working `.w3x` file with the blizzcon UI you are working on inside of this project.

If there is already one you could point it out in the README.md

Thank you for your work! 👍

**Comment by rufreakde** [comment]
echoisles-re1.w3x in the root directory has the UI. Maybe move it in a Demo folder :)

**Comment by yitao-yu** [comment]
Greetings
So I'm the one posting on Reddit
I'm sorry I just realized that all maps are in ./Test Bundle/
Maps with UI are in ./Test Bundle/With UI/
I'm sorry I did not mention that on Reddit

**Comment by rufreakde** [comment]
Ah I see, thanks! 
Still this should be written in the readme for other users that stumble upon this :)

**Comment by UIZorrot** [comment]
I will, thx for your mention！

发送自 Windows 10 版邮件应用

发件人: rufreakde
发送时间: 2020年4月17日 16:01
收件人: UIZorrot/War3re-inmap-graphic-enhance
抄送: Subscribed
主题: [UIZorrot/War3re-inmap-graphic-enhance] [Feature] Demo .w3x map withBlizzcon UI (#1)

Hey,
would be nice if there was a working .w3x file with the blizzcon UI you are working on inside of this project.
If there is already one you could point it out in the README.md
Thank you for your work! 👍
