### ISSUE TITLE
[bug] Game crash after enabling the mod

### ISSUE THREAD

**Issue by ain-soph** [UIZorrot/War3re-inmap-graphic-enhance#11]
English:  
When I install the mod and enable it, the first game is good. But the second game will always crash when I press `Start Game` (never reach the loading screen).

After I disable the mod, all games are good then.

--------------------
Chinese:  
开了这mod之后第一盘游戏没啥问题，但第二把必定报错，在我建好房间点开始游戏的时候（不会进入读条界面）。

## Environment
Mod version: v1.7  
Game version: v1.32.10.18067

OS: windows 11 21H2 (22000.376)
GPU: Nvidia RTX 2080
CPU: Intel Core i7-9700K

<img width="448" alt="image" src="https://user-images.githubusercontent.com/13214530/148295346-5f45a471-de44-4b99-bb5c-e5094915f1e7.png">

**Comment by UIZorrot** [comment]
修复了


| |
Zorrot Chen
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/6/2022 05:56，Ren ***@***.***> wrote：

English:
When I install the mod and enable it, the first game is good. But the second game will always crash when I press Start Game.

After I disable the mod, all games are good then.

Chinese:
开了这mod之后第一盘游戏没啥问题，但第二把必定报错，在我建好房间点开始游戏的时候（不会进入读条界面）。

Environment

V 1.7

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ain-soph** [comment]
Thanks for quick reply. I wonder where I could get the nightly version of the mod? I mean the version that fixes this issue.

**Comment by UIZorrot** [comment]
just redownload in official site




| |
Zorrot Chen
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/10/2022 03:00，Ren ***@***.***> wrote：

Thanks for quick reply. I wonder where I could get the nightly version of the mod? I mean the version that fixes this issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
