### ISSUE TITLE
游戏版本1.32.6.15355 不起作用

### ISSUE THREAD

**Issue by Jackwei9489** [UIZorrot/War3re-inmap-graphic-enhance#5]
重置，删除重装都不可以。确认一下这个版本是不是工作正常

**Comment by UIZorrot** [comment]
是的，晚上应该会更新

发送自 Windows 10 版邮件应用

发件人: Allen Wei
发送时间: 2020年6月6日 1:39
收件人: UIZorrot/War3re-inmap-graphic-enhance
抄送: Subscribed
主题: [UIZorrot/War3re-inmap-graphic-enhance] 游戏版本1.32.6.15355 不起作用 (#5)

重置，删除重装都不可以。确认一下这个版本是不是工作正常

**Comment by Jackwei9489** [comment]
已经fix，感谢
