### ISSUE TITLE
战役《月亮的女儿》泰兰德无法和弓箭手汇合

### ISSUE THREAD

**Issue by zhairuiyao15** [UIZorrot/War3re-inmap-graphic-enhance#6]
![image](https://user-images.githubusercontent.com/68763952/88471670-6ce39e80-cf3e-11ea-9a20-b72ac2e02196.png)

**Comment by UIZorrot** [comment]
Delete  :  _retail_\doodads\lordaeronsummer\terrain\barricade

发送自 Windows 10 版邮件应用

发件人: Ray Zhai
发送时间: 2020年7月26日 12:50
收件人: UIZorrot/War3re-inmap-graphic-enhance
抄送: Subscribed
主题: [UIZorrot/War3re-inmap-graphic-enhance] 战役《月亮的女儿》泰兰德无法和弓箭手汇合 (#6)

**Comment by zhairuiyao15** [comment]
感谢！已修复。
